name: csharp_nuget_publish
on:
  push:
    branches: ['main','develop']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        id: csharp_nuget_publish
        uses: JankwareDotCom/csharp_nuget_publish@0.2.16
        with: 
          PROJECT_FILE_PATHS: './src/FileParty.Core/FileParty.Core.csproj,./src/FileParty.Providers.FileSystem/FileParty.Providers.FileSystem.csproj,./src/FileParty.Providers.AWS.S3/FileParty.Providers.AWS.S3.csproj'
          NUGET_SOURCE: ${{secrets.JANKWARE_NUGET_SOURCE}}
          NUGET_KEY: ${{secrets.JANKWARE_NUGET_API_KEY}}
          #VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
          INCLUDE_SYMBOLS: 'true'
          TAG_COMMIT: 'develop,main'
          TAG_FORMAT: '*'
          BRANCH_VERSION_SUFFIXES: 'develop=-pre'
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
