name: csharp_nuget_publish
on:
  pull_request:
    branches: ['main','develop']
    types: [closed]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build and Publish Nuget Packages
        id: csharp_nuget_publish
        uses: JankwareDotCom/nuget_publish@0.4.0
        with: 
          PROJECT_FILE_PATHS: './src/FileParty.Core/FileParty.Core.csproj,./src/FileParty.Providers.FileSystem/FileParty.Providers.FileSystem.csproj,./src/FileParty.Providers.AWS.S3/FileParty.Providers.AWS.S3.csproj'
          NUGET_SOURCE: ${{secrets.JANKWARE_NUGET_SOURCE}}
          NUGET_KEY: ${{secrets.JANKWARE_NUGET_API_KEY}}
          #VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
          INCLUDE_SYMBOLS: 'true'
          TAG_COMMIT: 'develop,main'
          TAG_FORMAT: 'v*'
          BRANCH_VERSION_SUFFIXES: 'develop=pre-{yyoooHHmm}-*'
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
